blank_issues_enabled: false
contact_links:
  - name: "🔗 How to Use"
    url: https://github.com/katiem0/gh-organization-webhooks#readme
    about: Check out the list and create documentation for help.
  - name: "🔗 GitHub Migration Documentation"
    url: https://docs.github.com/en/migrations
    about: Learn about the migration process and best practices.